name: Angular Karma Publish Release to Dev
on:
  pull_request:
    branches:
      - main

jobs:
  run-e2e-test:
    name: run testcases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: run testcase
        run:  npm test -- --watch=false --browsers=ChromeHeadless
